# Generated by Django 5.2.1 on 2025-06-10 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category of a specific Menu Item', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Menu Item Category',
                'verbose_name_plural': 'Menu Item Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='A brief description of the menu item')),
                ('calories', models.IntegerField(default=0, help_text='Calories per 100g')),
                ('carbs', models.IntegerField(default=0, help_text='Carbohydrates per 100g')),
                ('protein', models.IntegerField(default=0, help_text='Protein per 100g')),
                ('fats', models.IntegerField(default=0, help_text='Fats per 100g')),
                ('category', models.ForeignKey(blank=True, help_text='The category this menu item belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.menuitemcategory')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
            },
        ),
        migrations.CreateModel(
            name='MenuItemPortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the portion ('Small', 'Regular', etc...)", max_length=100)),
                ('amount_in_grams_ml', models.IntegerField(default=100, help_text='Amount for this portion in grams or milliliters')),
                ('price', models.FloatField()),
                ('is_liquid', models.BooleanField(default=False)),
                ('menu_item', models.ForeignKey(help_text='The menu item this portion belongs to', on_delete=django.db.models.deletion.CASCADE, to='food.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Portion',
                'verbose_name_plural': 'Menu Item Portions',
                'unique_together': {('menu_item', 'name')},
            },
        ),
    ]
