# Generated by Django 5.2.1 on 2025-06-14 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemportion',
            name='discount_percent',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0, message='Discount cannot be negative.')]),
        ),
        migrations.AlterField(
            model_name='menuitemportion',
            name='price',
            field=models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(0.0, message='Price cannot be negative.')]),
        ),
    ]
