# Generated by Django 5.2.1 on 2025-06-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the image for this menu item', max_length=500, null=True),
        ),
    ]
