# Generated by Django 5.2.1 on 2025-06-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_menuitemportion_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitemcategory',
            options={'ordering': ['index'], 'verbose_name': 'Menu Item Category', 'verbose_name_plural': 'Menu Item Categories'},
        ),
        migrations.AddField(
            model_name='menuitemcategory',
            name='index',
            field=models.IntegerField(default=0, help_text='Which category shows up first'),
        ),
    ]
