# Generated by Django 5.2.1 on 2025-06-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_menuitemcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemportion',
            name='is_liquid',
        ),
        migrations.AddField(
            model_name='menuitemcategory',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the image for this category', max_length=500, null=True),
        ),
    ]
