# Generated by Django 5.2.1 on 2025-06-15 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_remove_menuitemportion_is_liquid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemportion',
            name='menu_item',
            field=models.ForeignKey(help_text='The menu item this portion belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='portions', to='food.menuitem'),
        ),
    ]
