# Generated by Django 5.2.1 on 2025-06-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_order_customer_address_order_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
